### PR TITLE
codespell: config, workflow and typos fixed

### PR DESCRIPTION
**Pull request by yarikoptic**
was just looking around ;-)

### CODE REVIEW

**Comment by jeremymanning** [comment]
Thanks @yarikoptic, these are great!

**Comment by jeremymanning** [comment]
@yarikoptic can we add "covert attention" to some sort of "ignore" list for code spell?  otherwise that check is just going to fail every time...

**Comment by yarikoptic** [comment]
done! odd that I didn't pick that up locally

**Review by paxtonfitzpatrick — APPROVED** [review]
This looks great, thanks @yarikoptic! I tend to ignore/disable my IDE's spellchecker (as you can see 🙃) because it's _so_ sensitive, so this seems like a good compromise. Also impressed with how quick the action ran!

**Pull request merged**
